import Foundation

enum DSAStrings {
    static let locale = "de"

    // MARK: - Lookup

    static func localized(_ key: String) -> String {
        if locale == "de", let de = translations[key] {
            return de
        }
        return englishFallback[key] ?? key
    }

    // MARK: - Field Labels (PersonalData, Experience, DerivedValues)

    private static let englishFallback: [String: String] = [
        // Experience
        "level":                "Level",
        "totalAP":              "Total AP",
        "availableAP":          "Available AP",
        "spentAP":              "Spent AP",
        // PersonalData
        "name":                 "Name",
        "family":               "Family",
        "birthplace":           "Birthplace",
        "birthdate":            "Birthdate",
        "age":                  "Age",
        "gender":               "Gender",
        "species":              "Species",
        "height":               "Height",
        "weight":               "Weight",
        "hairColor":            "Hair Color",
        "eyeColor":             "Eye Color",
        "culture":              "Culture",
        "socialStatus":         "Social Status",
        "profession":           "Profession",
        "title":                "Title",
        "characteristics":      "Characteristics",
        // DerivedValues
        "lebensenergie":        "Life Energy",
        "schicksalspunkte":     "Fate Points",
        "astralenergie":        "Astral Energy",
        "karmaenergie":         "Karma Energy",
        "seelenkraft":          "Spirit",
        "zähigkeit":            "Toughness",
        "ausweichen":           "Dodge",
        "initiative":           "Initiative",
        "geschwindigkeit":      "Speed",
        "wundschwelle":         "Wound Threshold",
        // Section Headers
        "experience":           "Experience",
        "personalData":         "Personal Data",
        "derivedValues":        "Derived Values",
        "advantages":           "Advantages",
        "disadvantages":        "Disadvantages",
        "generalSpecialAbilities": "General Special Abilities",
        "languages":            "Languages",
        "scripts":              "Scripts",
        "combatTechniques":     "Combat Techniques",
        "combatSpecialAbilities": "Combat Special Abilities",
        "equipment":            "Equipment",
        "meleeWeapons":         "Melee Weapons",
        "rangedWeapons":        "Ranged Weapons",
        "shields":              "Shields",
        "armor":                "Armor",
        "money":                "Money",
        "mount":                "Mount",
        // Mount fields
        "mountName":            "Name",
        "mountType":            "Type",
        "mountSize":            "Size",
        "mountLifeEnergy":      "Life Energy",
        "mountInitiative":      "Initiative",
        "mountSpeed":           "Speed",
        "mountAttacks":         "Attacks",
        "mountTalents":         "Talents",
        "mountSpecialAbilities": "Special Abilities",
        // Group headers (top-level tabs)
        "groupPersonalData":    "Personal Data",
        "groupTalents":         "Talents",
        "groupCombat":          "Combat",
        "groupEquipment":       "Equipment",
        // Money
        "dukaten":              "Ducats",
        "silbertaler":          "Silver Talers",
        "heller":               "Hellers",
        "kreuzer":              "Kreuzers",
        // Combat
        "combat":               "Combat",
        "round":                "Round",
        "lifePoints":           "Life Points",
        "lifePoints.short":     "LP",
        "action":               "Action",
        "attack":               "Attack",
        "parry":                "Parry",
        "dodge":                "Dodge",
        "newAction":            "New Action",
        "newInitiative":        "New Initiative",
        "unarmed":              "Unarmed",
        "confirmation":         "Confirmation",
        "tapToRoll":            "Tap to roll",
        "modifier":             "Mod",
        "new":                  "New",
        "round.label":          "ROUND",
        "lifePoints.label":     "LIFE POINTS",
        "status.label":         "STATUS",
        "action.label":         "ACTION",
        "unarmed.label":        "UNARMED",
        "selectWeapon":         "Select Weapon",
        "selectShield":         "Select Shield",
        "noShield":             "No Shield",
        "criticalSuccess":      "!!! Critical Success!",
        "criticalFumble":       "!!! Critical Fumble!",
        "success":              "Success",
        "failure":              "Failure",
        "selectEquipment":      "Select Equipment",
        "offHandWeapon":        "OFF-HAND",
        "dualAttack":           "Both Weapons",
        "singleAttack":         "One Weapon",
        "oneHanded":            "One-Handed",
        "twoHanded":            "Two-Handed (+1 TP, −1 PA)",
        "dualAttackPenalty":    "Dual-attack penalty",
        "offHandPenalty":       "Off-hand penalty",
        "advantageousPosition": "Advantageous Position (+2)",
        "fumbleSecondLost":     "Fumble! Second attack lost.",
        "selectParryWeapon":    "Parry With",
        "shields.label":        "SHIELDS",
        // Rulebook
        "rulebook":             "Rulebook",
        "backToHero":           "Back to Hero",
        "backToRulebook":       "Back to Rulebook",
        "back":                 "Back",
        "ruleNotFound":         "Rule not found",
        "ruleLoadError":        "The rule could not be loaded.",
        "effects":              "Effects",
        "searchRules":          "Search rules…",
        "searchCommands":       "Search commands…",
        "noResults":            "No results",
        // HeroList
        "heroes":               "Heroes",
        "noHeroes":             "No Heroes",
        "importHero":           "Import Hero",
        "importHint":           "Import a JSON or YAML file to add your first hero.",
        "selectHint":           "Select a hero or the rulebook from the list.",
        // HeroSettings
        "heroSettings":         "Hero Settings",
        "colorScheme":          "Color Scheme",
        "colorSchemeAutomatic": "Automatic (from profession)",
        "close":                "Close",
        // TalentProbe
        "probe":                "Probe",
        "unknownTalent":        "Unknown Talent",
        // Regeneration & Healing
        "regeneration":         "Regeneration",
        "improvedRegen":        "Improved Regen.",
        "healing":              "Healing",
        "healingSourcePlaceholder": "Source (e.g. Potion, Balm...)",
        "mountHealing":         "Mount: Healing",
        // Rule categories (singular)
        "cat.advantage":        "Advantage",
        "cat.disadvantage":     "Disadvantage",
        "cat.special_ability":  "Special Ability",
        "cat.combat_technique": "Combat Technique",
        "cat.skill":            "Skill",
        "cat.condition":        "Condition",
        "cat.state":            "State",
        // Rule categories (plural)
        "cats.advantage":       "Advantages",
        "cats.disadvantage":    "Disadvantages",
        "cats.special_ability": "Special Abilities",
        "cats.combat_technique":"Combat Techniques",
        "cats.skill":           "Skills",
        "cats.condition":       "Conditions",
        "cats.state":           "States",
        "cat.spell":            "Spell",
        "cat.liturgy":          "Liturgy",
        "cats.spell":           "Spells",
        "cats.liturgy":         "Liturgies",

        "spellCheck":           "Check",
        "spellIC":              "Improvement Cost",
        "spellCastingTime":     "Casting Time",
        "spellAeCost":          "AE Cost",
        "liturgyTime":          "Liturgy Time",
        "liturgyCost":          "KP Cost",
        "spellRange":           "Range",
        "spellDuration":        "Duration",
        "spellTarget":          "Target",
        // Damage & Armor
        "takeDamage":           "Take Damage",
        "takeDamage.label":     "TAKE DAMAGE",
        "tp":                   "TP",
        "rs":                   "RS",
        "equip":                "Equip",
        "unequip":              "Unequip",
        "armorSelection":       "Armor Selection",
        "armorSelection.label": "ARMOR",
        "continue":             "Continue",
        "confirm":              "Confirm",
        "noArmor":              "No armor available",
        "equipped":             "Equipped",
        "protectionValue":      "RS",
        "encumbrance":          "BE",
        "lpLost":               "LP lost",
        "absorbed":             "Armor absorbs all damage",
        "changeLoadout":        "Change Loadout",
        // Combat Maneuvers
        "combatSetup":          "Combat Setup",
        "combatSetup.label":    "COMBAT SETUP",
        "formation.label":      "FORMATION",
        "mount.label":          "MOUNT",
        "mounted":              "Mounted",
        "announcement":         "Announcement",
        "announcement.label":   "MANEUVER",
        "maneuver.normal":      "Normal",
        "maneuver.finte":       "Feint",
        "maneuver.wuchtschlag": "Powerful Blow",
        "maneuver.vorstoss":    "Thrust",
        "maneuver.schildspalter":"Shield Splitter",
        "maneuver.sturmangriff":"Mounted Charge",
        "plaenkler":            "Skirmisher Formation",
        "plaenklerAT":          "+1 AT",
        "plaenklerAW":          "+1 Dodge",
        "noDefenseWarning":     "No defense this round!",
        "opponentPA":           "Opponent PA",
        "damageBonus":          "Damage",
        "targetShield":         "Damage targets shield SP",
        "mightyBlow":           "Mighty Blow: On hit, medium/small opponents must pass Feat of Strength or fall prone (penalty -%d).",
        "mightyBlowNoPenalty":  "Mighty Blow: On hit, medium/small opponents must pass Feat of Strength or fall prone. Parry does not help — only Dodge avoids it entirely.",
        "calculation.label":    "CALCULATION",
        "additional.label":     "ADDITIONAL",
        "source.basis":         "Base",
        "source.belastung":     "Encumbrance",
        "source.schmerz":       "Pain",
        "source.vorteilhaft":   "Adv. Position",
        "source.golgariten":    "Golgariten",
        "source.plaenkler":     "Skirmisher",
        "source.finte":         "Feint",
        "source.wuchtschlag":   "Powerful Blow",
        "source.vorstoss":      "Thrust",
        "source.sturmangriff":  "Mounted Charge",
        "source.dualAttack":    "Dual-attack",
        "source.offHand":       "Off-hand",
        "source.additional":    "Additional",
        "source.mounted":       "Mounted",
        "source.shield":        "Shield",
        "mountAttacks.label":   "MOUNT ATTACKS",
        "aufmerksamkeitHint":   "Aufmerksamkeit: +2 to avoid surprise",
        "schmerz.label":        "Pain",
        "schmerz.none":         "No pain",
        "schmerz.I":            "Pain I",
        "schmerz.II":           "Pain II",
        "schmerz.III":          "Pain III",
        "schmerz.IV":           "Incapacitated",
        "chargeBonus":          "Charge bonus",
        "galoppConfirm":        "Is your mount in gallop?",
        "reitenCheck":          "Reiten (Kampfmanöver) Check",
        "reitenCheckPrompt":    "Did the Reiten check succeed?",
        "reitenCheckPassed":    "Reiten check passed!",
        "reitenCheckFailed":    "Reiten check failed!",
        "rollReitenCheck":      "Roll Reiten Check",
        "mountTakesDamage":     "Mount Takes Damage",
        "mountDamage.sp":       "SP received",
        "mountDamage.penalty":  "Check penalty: %d",
        "mountDamage.apply":    "Apply & Check",
        "mountDamage.sturz":    "Fall! The rider is dismounted.",
        "mountDamage.noPenalty": "No additional penalty",
        "niederreiten":         "Trample",
        "niederreiten.info":    "Trample can only be defended by dodging.",
        "sturmangriffPferd":    "Mounted Charge",
        "sturmangriffPferd.info": "Mounted Charge cannot be parried with weapons — only shield parry or dodge.",
        "mountAttacksGroup":    "MOUNT ATTACKS",
        "heroAttacksGroup":     "YOUR ATTACKS",
        // Subfield labels (weapons, armor)
        "combatTechnique":      "Combat Technique",
        "damage":               "Damage",
        "reach":                "Reach",
        "range":                "Range",
        "structurePoints":      "SP",
        // Combat section labels
        "meleeWeapons.label":   "MELEE WEAPONS",
        "basis.label":          "BASICS",
        "damage.label":         "DAMAGE",
        "mainWeapon":           "MAIN WEAPON",
        "shieldOption":         "SHIELD",
        "hero":                 "Hero",
        // Misc UI
        "current":              "Current",
        "tierPrefix":           "Level",
        "rolling":              "Rolling...",
        "confirmIni":           "Confirm  →  INI",
        "roundPrefix":          "Round",
        "apPrefix":             "AP",
        "levelsPrefix":         "Levels",
        "importError":          "Import Error",
        "unknownError":         "An unknown error occurred.",
        "ok":                   "OK",
        "yes":                  "Yes",
        "no":                   "No",
        "diceRoll":             "Roll Dice",
        "diceCount":            "Count",
        "diceSides":            "Sides",

        // MARK: - Combat Overhaul

        // Beengte Umgebung
        "beengteUmgebung":              "Confined Space",
        "beengteUmgebung.label":        "ENVIRONMENT",

        // Weapon Reach
        "opponentReach.label":          "OPPONENT REACH",
        "source.reach":                 "Reach",

        // Opponent Defense
        "opponentDefense":              "Opponent Defense",
        "opponentDefense.parried":      "Parried",
        "opponentDefense.dodged":       "Dodged",
        "opponentDefense.hitThrough":   "Hit goes through",
        "opponentDefense.halved":       "Opponent defense halved",
        "opponentDefense.doubleDamage": "DP doubled",
        "opponentDefense.noWeaponParry":"No weapon parry possible",
        "opponentDefense.schusswaffe":  "Ranged weapon: Defense –4",
        "opponentDefense.wurfwaffe":    "Thrown weapon: Defense –2",
        "opponentDefense.shieldParry":  "Parried (Shield)",
        "proceedToDefense":             "Proceed to Defense",

        // Schicksalspunkte
        "schip.reroll":                 "Fate Point: Reroll",
        "schip.damageReroll":           "Fate Point: Reroll D6",
        "schip.defenseBoost":           "Boost Defense (+4)",
        "schip.ignoreZustand":          "Ignore Condition",
        "source.schipDefense":          "Fate Point",
        "schip.label":                  "FATE POINTS",
        "schip.remaining":              "Fate Points left",

        // Fumble
        "fumble.title":                 "Fumble!",
        "fumble.takeDamage":            "Take 1D6+2 SP",
        "fumble.rollTable":             "Roll fumble table",
        "fumble.tableResult":           "Result",
        "fumble.spIgnoresRS":           "SP not reduced by armor",

        // Multiple Defenses
        "source.multipleDefense":       "Multiple Defense",

        // Passierschlag
        "passierschlag":                "Free Strike",
        "passierschlag.info":           "AT –4, no maneuvers, no critical successes/fumbles",
        "source.passierschlag":         "Free Strike",

        // Flucht
        "flucht":                       "Flee",
        "flucht.info":                  "Body Control check (combat maneuver)",
        "flucht.opponents":             "Opponents in attack range",
        "flucht.success":               "Succeeded — GS movement",
        "flucht.failure":               "Failed — GS/2 movement, free strike suffered",
        "flucht.succeeded":             "Succeeded",
        "flucht.failed":                "Failed",

        // Fernkampf
        "rangedAttack":                 "Ranged Attack",
        "fernkampf":                    "Ranged Combat",
        "fernkampf.setup":              "Prepare Ranged Attack",
        "fernkampf.distanz":            "DISTANCE",
        "fernkampf.distanz.nah":        "Close",
        "fernkampf.distanz.mittel":     "Medium",
        "fernkampf.distanz.weit":       "Far",
        "fernkampf.groesse":            "SIZE",
        "fernkampf.groesse.winzig":     "Tiny",
        "fernkampf.groesse.klein":      "Small",
        "fernkampf.groesse.mittel":     "Medium",
        "fernkampf.groesse.gross":      "Large",
        "fernkampf.groesse.riesig":     "Huge",
        "fernkampf.bewegungZiel":       "TARGET MOVEMENT",
        "fernkampf.ziel.still":         "Still",
        "fernkampf.ziel.leicht":        "Slight",
        "fernkampf.ziel.schnell":       "Fast",
        "fernkampf.ziel.haken":         "Zigzag",
        "fernkampf.bewegungSchuetze":   "SHOOTER MOVEMENT",
        "fernkampf.schuetze.steht":     "Standing",
        "fernkampf.schuetze.geht":      "Walking",
        "fernkampf.schuetze.rennt":     "Running",
        "fernkampf.sicht":              "VISIBILITY",
        "fernkampf.sicht.klar":         "Clear",
        "fernkampf.sicht.stufe1":       "Level 1",
        "fernkampf.sicht.stufe2":       "Level 2",
        "fernkampf.sicht.stufe3":       "Level 3",
        "fernkampf.kampfgetuemmel":     "Melee",
        "fernkampf.zielen":             "AIM",
        "fernkampf.zielen.0":           "No Aiming",
        "fernkampf.zielen.1":           "1 Action (+2)",
        "fernkampf.zielen.2":           "2 Actions (+4)",
        "fernkampf.vomPferd":           "FROM HORSEBACK",
        "fernkampf.pferd.steht":        "Standing",
        "fernkampf.pferd.schritt":      "Walk",
        "fernkampf.pferd.galopp":       "Gallop",
        "fernkampf.rangedWeapons.label":"RANGED WEAPONS",
        "source.distanz":               "Distance",
        "source.groesse":               "Size",
        "source.bewegungZiel":          "Target Movement",
        "source.bewegungSchuetze":      "Shooter Movement",
        "source.sicht":                 "Visibility",
        "source.kampfgetuemmel":        "Melee",
        "source.zielen":                "Aiming",
        "source.vomPferd":              "From Horseback",

        // Combat session
        "endCombat":                    "End Combat",
        "endCombat.confirm":            "Really end combat?",

        // Adventure & Weather
        "adventures":                   "Adventures",
        "newAdventure":                 "New Adventure",
        "adventureName":                "Name",
        "adventureRegion":              "Region",
        "adventureStartDate":           "Start Date",
        "adventureDesert":              "Desert",
        "adventureWindy":               "Windy",
        // Macro regions
        "macro.hoherNorden":            "Far North",
        "macro.hochgebirge":            "High Mountains",
        "macro.nordaventurien":         "Northern Aventuria",
        "macro.zentralaventurien":      "Central Aventuria",
        "macro.tulamidenlande":         "Tulamidean Lands",
        "macro.suedaventurien":         "Southern Aventuria",
        "macro.tieferSueden":           "Deep South & Isles",
        // Climate archetypes
        "climate.polar":                "Polar",
        "climate.subarctic":            "Subarctic",
        "climate.highMountainIce":      "Glacial Mountains",
        "climate.highMountain":         "High Mountains",
        "climate.coldCoast":            "Cold Coast",
        "climate.coldContinental":      "Cold Continental",
        "climate.temperate":            "Temperate",
        "climate.mediterranean":        "Mediterranean",
        "climate.semiArid":             "Semi-Arid Steppe",
        "climate.desert":               "Desert",
        "climate.subtropicalHot":       "Hot Subtropical",
        "climate.tropicalHumid":        "Tropical Humid",
        "climate.tropicalSea":          "Tropical Sea",
        // Regions
        "region.ewigesEis":             "Eternal Ice",
        "region.nivesenland":           "Nivese Land, Tundra",
        "region.gjalskerland":          "Gjalskerland",
        "region.ehernesSchwert":        "Heights of the Iron Sword",
        "region.raschtulswall":         "Heights of the Raschtulswall",
        "region.thorwal":               "Thorwal",
        "region.bornland":              "Bornland",
        "region.svelltland":            "Svellt Valley",
        "region.orkland":               "Orkland",
        "region.mittelreich":           "Central Middenrealm",
        "region.streitendeKoenigreiche": "Warring Kingdoms, Weiden",
        "region.elfenlande":            "Elven Lands",
        "region.aranien":               "Aranian Steppe",
        "region.khom":                  "Khôm Desert",
        "region.mhanadiTal":            "Mhanadi Valley, Unau",
        "region.almada":                "Almada",
        "region.horasreich":            "Horasian Empire, Liebliches Feld",
        "region.ersteSonne":            "Realm of the First Sun",
        "region.zyklopeninseln":        "Cyclopean Isles",
        "region.meridiana":             "Al'Anfa, Meridiana",
        "region.echsensuempfe":         "Lizard Swamps",
        "region.maraskan":              "Maraskan",
        "region.suedmeer":              "Altoum, Spice Isles, South Sea",
        "nextDay":                      "Next Day",
        "generateDays":                 "Generate Days…",
        "setDate":                      "Set Date…",
        "export":                       "Export",
        "weather.add":                  "Add Weather",
        "weather.empty":                "Add weather to begin",
        "weather.rules":                "Rules",
        "adventureDefaultRegion":       "Default Region",
        "weather.rules.title":          "How weather works",
        "weather.rules.body":           "Night temperature = day high minus the diurnal range. Dry, clear, calm areas (desert, high mountains) cool down sharply at night; cloudy, humid or windy areas (coast, swamps) barely cool. Each region has a climate that sets its base temperature, range, humidity and wind.",
        "weather.rules.clouds":         "Clouds trap heat → smaller night drop.",
        "weather.rules.wind":           "Wind mixes the air → smaller night drop.",
        "weather.rules.climate":        "Climate sets the clear-sky range.",
        "settings":                     "Settings",
        "dayCount":                     "Number of Days",
        "timeJump":                     "Time Jump",
        "generate":                     "Generate",
        "cancel":                       "Cancel",
        "create":                       "Create",
        // Weather display
        "weather.clouds.none":          "Clear",
        "weather.clouds.few":           "Few Clouds",
        "weather.clouds.lots":          "Cloudy",
        "weather.clouds.all":           "Overcast",
        "weather.wind.none":            "Calm",
        "weather.wind.light":           "Light Wind",
        "weather.wind.soft":            "Soft Wind",
        "weather.wind.fresh":           "Fresh Wind",
        "weather.wind.cool":            "Cool Wind",
        "weather.wind.strong":          "Strong Wind",
        "weather.wind.storm":           "Storm",
        "weather.rain.none":            "No Precipitation",
        "weather.rain.little":          "Light Rain",
        "weather.rain.lots":            "Heavy Rain",
        "weather.rain.all":             "Continuous Rain",
        "weather.field.clouds":         "Clouds",
        "weather.field.wind":           "Wind",
        "weather.field.rain":           "Precipitation",
        "weather.dayTemp":              "Day",
        "weather.nightTemp":            "Night",
        "weather.range":                "Range",
        "weather.edited":               "edited",
        "weather.reason.dry":           "dry",
        "weather.reason.humid":         "humid",
        "weather.reason.clear":         "clear",
        "weather.reason.cloudy":        "clouds",
        "weather.reason.windy":         "wind",
        "weather.reroll":               "Re-roll",
        "weather.editValues":           "Override Values",
        "save":                         "Save",
        // Magic sections
        "groupMagic":                   "Magic & Karma",
        "spells.section":               "Spells",
        "liturgies.section":            "Liturgies",
        "cantrips.section":             "Cantrips",
        "blessings.section":            "Blessings",
    ]

    private static let translations: [String: String] = [
        // Experience
        "level":                "Stufe",
        "totalAP":              "AP gesamt",
        "availableAP":          "AP verfügbar",
        "spentAP":              "AP ausgegeben",
        // PersonalData
        "name":                 "Name",
        "family":               "Familie",
        "birthplace":           "Geburtsort",
        "birthdate":            "Geburtsdatum",
        "age":                  "Alter",
        "gender":               "Geschlecht",
        "species":              "Spezies",
        "height":               "Größe",
        "weight":               "Gewicht",
        "hairColor":            "Haarfarbe",
        "eyeColor":             "Augenfarbe",
        "culture":              "Kultur",
        "socialStatus":         "Sozialstatus",
        "profession":           "Profession",
        "title":                "Titel",
        "characteristics":      "Eigenschaften",
        // DerivedValues
        "lebensenergie":        "Lebensenergie",
        "schicksalspunkte":     "Schicksalspunkte",
        "astralenergie":        "Astralenergie",
        "karmaenergie":         "Karmaenergie",
        "seelenkraft":          "Seelenkraft",
        "zähigkeit":            "Zähigkeit",
        "ausweichen":           "Ausweichen",
        "initiative":           "Initiative",
        "geschwindigkeit":      "Geschwindigkeit",
        "wundschwelle":         "Wundschwelle",
        // Section Headers
        "experience":           "Erfahrung",
        "personalData":         "Persönliche Daten",
        "derivedValues":        "Abgeleitete Werte",
        "advantages":           "Vorteile",
        "disadvantages":        "Nachteile",
        "generalSpecialAbilities": "Allgemeine Sonderfertigkeiten",
        "languages":            "Sprachen",
        "scripts":              "Schriften",
        "combatTechniques":     "Kampftechniken",
        "combatSpecialAbilities": "Kampf-Sonderfertigkeiten",
        "equipment":            "Ausrüstung",
        "meleeWeapons":         "Nahkampfwaffen",
        "rangedWeapons":        "Fernkampfwaffen",
        "shields":              "Schilde",
        "armor":                "Rüstungen",
        "money":                "Geld",
        "mount":                "Reittier",
        // Mount fields
        "mountName":            "Name",
        "mountType":            "Art",
        "mountSize":            "Größe",
        "mountLifeEnergy":      "Lebensenergie",
        "mountInitiative":      "Initiative",
        "mountSpeed":           "Geschwindigkeit",
        "mountAttacks":         "Angriffe",
        "mountTalents":         "Talente",
        "mountSpecialAbilities": "Sonderfertigkeiten",
        // Group headers (top-level tabs)
        "groupPersonalData":    "Persönliche Daten",
        "groupTalents":         "Talente",
        "groupCombat":          "Kampf",
        "groupEquipment":       "Ausrüstung",
        // Money
        "dukaten":              "Dukaten",
        "silbertaler":          "Silbertaler",
        "heller":               "Heller",
        "kreuzer":              "Kreuzer",
        // Combat
        "combat":               "Kampf",
        "round":                "Runde",
        "lifePoints":           "Lebenspunkte",
        "lifePoints.short":     "LP",
        "action":               "Aktion",
        "attack":               "Angriff",
        "parry":                "Parieren",
        "dodge":                "Ausweichen",
        "newAction":            "Neue Aktion",
        "newInitiative":        "Neue Initiative",
        "unarmed":              "Waffenlos",
        "confirmation":         "Bestätigung",
        "tapToRoll":            "Antippen zum Würfeln",
        "modifier":             "Mod",
        "new":                  "Neu",
        "round.label":          "RUNDE",
        "lifePoints.label":     "LEBENSPUNKTE",
        "status.label":         "STATUS",
        "action.label":         "AKTION",
        "unarmed.label":        "WAFFENLOS",
        "selectWeapon":         "Waffe wählen",
        "selectShield":         "Schild wählen",
        "noShield":             "Kein Schild",
        "criticalSuccess":      "!!! Kritischer Erfolg!",
        "criticalFumble":       "!!! Kritischer Patzer!",
        "success":              "Erfolg",
        "failure":              "Misserfolg",
        "selectEquipment":      "Ausrüstung wählen",
        "offHandWeapon":        "NEBENHAND",
        "dualAttack":           "Beide Waffen",
        "singleAttack":         "Eine Waffe",
        "oneHanded":            "Einhändig",
        "twoHanded":            "Zweihändig (+1 TP, −1 PA)",
        "dualAttackPenalty":    "Beidhändig-Abzug",
        "offHandPenalty":       "Nebenhand-Abzug",
        "advantageousPosition": "Vorteilhafte Position (+2)",
        "fumbleSecondLost":     "Patzer! Zweiter Angriff entfällt.",
        "selectParryWeapon":    "Parieren mit",
        "shields.label":        "SCHILDE",
        // Rulebook
        "rulebook":             "Regelbuch",
        "backToHero":           "Zurück zum Helden",
        "backToRulebook":       "Zurück zum Regelbuch",
        "back":                 "Zurück",
        "ruleNotFound":         "Regel nicht gefunden",
        "ruleLoadError":        "Die Regel konnte nicht geladen werden.",
        "effects":              "Effekte",
        "searchRules":          "Regel suchen…",
        "searchCommands":       "Befehl suchen…",
        "noResults":            "Keine Ergebnisse",
        // HeroList
        "heroes":               "Helden",
        "noHeroes":             "Keine Helden",
        "importHero":           "Held importieren",
        "importHint":           "Importiere eine JSON- oder YAML-Datei, um deinen ersten Helden hinzuzufügen.",
        "selectHint":           "Wähle einen Helden oder das Regelbuch aus der Liste.",
        // HeroSettings
        "heroSettings":         "Heldeneinstellungen",
        "colorScheme":          "Farbschema",
        "colorSchemeAutomatic": "Automatisch (aus Profession)",
        "close":                "Schließen",
        // TalentProbe
        "probe":                "Probe",
        "unknownTalent":        "Unbekanntes Talent",
        // Regeneration & Healing
        "regeneration":         "Regenerieren",
        "improvedRegen":        "Verb. Regen.",
        "healing":              "Heilung",
        "healingSourcePlaceholder": "Quelle (z.B. Heiltrank, Balsam...)",
        "mountHealing":         "Reittier: Heilung",
        // Rule categories (singular)
        "cat.advantage":        "Vorteil",
        "cat.disadvantage":     "Nachteil",
        "cat.special_ability":  "Sonderfertigkeit",
        "cat.combat_technique": "Kampftechnik",
        "cat.skill":            "Talent",
        "cat.condition":        "Zustand",
        "cat.state":            "Status",
        // Rule categories (plural)
        "cats.advantage":       "Vorteile",
        "cats.disadvantage":    "Nachteile",
        "cats.special_ability": "Sonderfertigkeiten",
        "cats.combat_technique":"Kampftechniken",
        "cats.skill":           "Talente",
        "cats.condition":       "Zustände",
        "cats.state":           "Status",
        "cat.spell":            "Zauber",
        "cat.liturgy":          "Liturgie",
        "cats.spell":           "Zauber",
        "cats.liturgy":         "Liturgien",

        "spellCheck":           "Probe",
        "spellIC":              "Steigerungsfaktor",
        "spellCastingTime":     "Zauberdauer",
        "spellAeCost":          "AsP-Kosten",
        "liturgyTime":          "Liturgiedauer",
        "liturgyCost":          "KaP-Kosten",
        "spellRange":           "Reichweite",
        "spellDuration":        "Wirkungsdauer",
        "spellTarget":          "Zielkategorie",
        // Damage & Armor
        "takeDamage":           "Schaden nehmen",
        "takeDamage.label":     "SCHADEN NEHMEN",
        "tp":                   "TP",
        "rs":                   "RS",
        "equip":                "Anlegen",
        "unequip":              "Ablegen",
        "armorSelection":       "Rüstungsauswahl",
        "armorSelection.label": "RÜSTUNG",
        "continue":             "Weiter",
        "confirm":              "Bestätigen",
        "noArmor":              "Keine Rüstung vorhanden",
        "equipped":             "Angelegt",
        "protectionValue":      "RS",
        "encumbrance":          "BE",
        "lpLost":               "LP verloren",
        "absorbed":             "Rüstung absorbiert allen Schaden",
        "changeLoadout":        "Ausrüstung wechseln",
        // Combat Maneuvers
        "combatSetup":          "Kampfvorbereitung",
        "combatSetup.label":    "KAMPFVORBEREITUNG",
        "formation.label":      "FORMATION",
        "mount.label":          "REITTIER",
        "mounted":              "Beritten",
        "announcement":         "Ansage",
        "announcement.label":   "MANÖVER",
        "maneuver.normal":      "Normal",
        "maneuver.finte":       "Finte",
        "maneuver.wuchtschlag": "Wuchtschlag",
        "maneuver.vorstoss":    "Vorstoß",
        "maneuver.schildspalter":"Schildspalter",
        "maneuver.sturmangriff":"Sturmangriff",
        "plaenkler":            "Plänkler-Formation",
        "plaenklerAT":          "+1 AT",
        "plaenklerAW":          "+1 AW",
        "noDefenseWarning":     "Keine Verteidigung diese Runde!",
        "opponentPA":           "Gegner PA",
        "damageBonus":          "Schaden",
        "targetShield":         "Schaden gegen Schild-SP",
        "mightyBlow":           "Mächtiger Schlag: Bei Treffer müssen Gegner (mittel/klein) Kraftakt bestehen oder erhalten Status Liegend (Erschwernis -%d). Parade hilft nicht — nur Ausweichen schützt vollständig.",
        "mightyBlowNoPenalty":  "Mächtiger Schlag: Bei Treffer müssen Gegner (mittel/klein) Kraftakt bestehen oder erhalten Status Liegend. Parade hilft nicht — nur Ausweichen schützt vollständig.",
        "calculation.label":    "BERECHNUNG",
        "additional.label":     "ZUSÄTZLICH",
        "source.basis":         "Basis",
        "source.belastung":     "Belastung",
        "source.schmerz":       "Schmerz",
        "source.vorteilhaft":   "Vorteilh. Pos.",
        "source.golgariten":    "Golgariten",
        "source.plaenkler":     "Plänkler",
        "source.finte":         "Finte",
        "source.wuchtschlag":   "Wuchtschlag",
        "source.vorstoss":      "Vorstoß",
        "source.sturmangriff":  "Sturmangriff",
        "source.dualAttack":    "Beidhändig",
        "source.offHand":       "Nebenhand",
        "source.additional":    "Zusätzlich",
        "source.mounted":       "Beritten",
        "source.shield":        "Schild",
        "mountAttacks.label":   "REITTIER-ANGRIFFE",
        "aufmerksamkeitHint":   "Aufmerksamkeit: +2 auf Überraschung vermeiden",
        "schmerz.label":        "Schmerz",
        "schmerz.none":         "Kein Schmerz",
        "schmerz.I":            "Schmerz I",
        "schmerz.II":           "Schmerz II",
        "schmerz.III":          "Schmerz III",
        "schmerz.IV":           "Handlungsunfähig",
        "chargeBonus":          "Sturmangriffsbonus",
        "galoppConfirm":        "Ist dein Reittier im Galopp?",
        "reitenCheck":          "Reiten (Kampfmanöver)-Probe",
        "reitenCheckPrompt":    "Wurde die Reiten-Probe bestanden?",
        "reitenCheckPassed":    "Reiten-Probe bestanden!",
        "reitenCheckFailed":    "Reiten-Probe nicht bestanden!",
        "rollReitenCheck":      "Reiten-Probe würfeln",
        "mountTakesDamage":     "Reittier erleidet Schaden",
        "mountDamage.sp":       "Erlittene SP",
        "mountDamage.penalty":  "Erschwernis: %d",
        "mountDamage.apply":    "Anwenden & Probe",
        "mountDamage.sturz":    "Sturz! Der Reiter wird abgeworfen.",
        "mountDamage.noPenalty": "Keine zusätzliche Erschwernis",
        "niederreiten":         "Niederreiten",
        "niederreiten.info":    "Niederreiten kann nur durch Ausweichen verteidigt werden.",
        "sturmangriffPferd":    "Sturmangriff zu Pferd",
        "sturmangriffPferd.info": "Sturmangriff zu Pferd kann nicht mit Waffen pariert werden — nur Schildparade oder Ausweichen.",
        "mountAttacksGroup":    "REITTIER-ANGRIFFE",
        "heroAttacksGroup":     "EIGENE ANGRIFFE",
        // Subfield labels (weapons, armor)
        "combatTechnique":      "Kampftechnik",
        "damage":               "Schaden",
        "reach":                "Reichweite",
        "range":                "Reichweite",
        "structurePoints":      "SP",
        // Combat section labels
        "meleeWeapons.label":   "NAHKAMPFWAFFEN",
        "basis.label":          "BASIS",
        "damage.label":         "SCHADEN",
        "mainWeapon":           "HAUPTWAFFE",
        "shieldOption":         "SCHILD",
        "hero":                 "Held",
        // Misc UI
        "current":              "Aktuell",
        "tierPrefix":           "Stufe",
        "rolling":              "Würfeln...",
        "confirmIni":           "Bestätigen  →  INI",
        "roundPrefix":          "Runde",
        "apPrefix":             "AP",
        "levelsPrefix":         "Stufen",
        "importError":          "Importfehler",
        "unknownError":         "Ein unbekannter Fehler ist aufgetreten.",
        "ok":                   "OK",
        "yes":                  "Ja",
        "no":                   "Nein",
        "pets":                 "Tiere",
        "diceRoll":             "Würfeln",
        "diceCount":            "Anzahl",
        "diceSides":            "Seiten",

        // MARK: - Combat Overhaul

        // Beengte Umgebung
        "beengteUmgebung":              "Beengte Umgebung",
        "beengteUmgebung.label":        "UMGEBUNG",

        // Weapon Reach
        "opponentReach.label":          "GEGNER-REICHWEITE",
        "source.reach":                 "Reichweite",

        // Opponent Defense
        "opponentDefense":              "Verteidigung des Gegners",
        "opponentDefense.parried":      "Pariert",
        "opponentDefense.dodged":       "Ausgewichen",
        "opponentDefense.hitThrough":   "Treffer geht durch",
        "opponentDefense.halved":       "Gegner Verteidigung halbiert",
        "opponentDefense.doubleDamage": "TP verdoppelt",
        "opponentDefense.noWeaponParry":"Keine Parade mit Waffe möglich",
        "opponentDefense.schusswaffe":  "Schusswaffe: Verteidigung –4",
        "opponentDefense.wurfwaffe":    "Wurfwaffe: Verteidigung –2",
        "opponentDefense.shieldParry":  "Pariert (Schild)",
        "proceedToDefense":             "Weiter zur Verteidigung",

        // Schicksalspunkte
        "schip.reroll":                 "Schip: Neuer Wurf",
        "schip.damageReroll":           "Schip: W6 wiederholen",
        "schip.defenseBoost":           "Verteidigung stärken (+4)",
        "schip.ignoreZustand":          "Zustand ignorieren",
        "source.schipDefense":          "Schicksalspunkt",
        "schip.label":                  "SCHICKSALSPUNKTE",
        "schip.remaining":              "Schips übrig",

        // Fumble
        "fumble.title":                 "Patzer!",
        "fumble.takeDamage":            "1W6+2 SP nehmen",
        "fumble.rollTable":             "Patzertabelle würfeln",
        "fumble.tableResult":           "Ergebnis",
        "fumble.spIgnoresRS":           "SP werden nicht durch RS reduziert",

        // Multiple Defenses
        "source.multipleDefense":       "Mehrfache Verteidigung",

        // Passierschlag
        "passierschlag":                "Passierschlag",
        "passierschlag.info":           "AT –4, keine Manöver, keine Kritischen Erfolge/Patzer",
        "source.passierschlag":         "Passierschlag",

        // Flucht
        "flucht":                       "Flucht",
        "flucht.info":                  "Probe auf Körperbeherrschung (Kampfmanöver)",
        "flucht.opponents":             "Gegner in Angriffsdistanz",
        "flucht.success":               "Gelungen — GS Schritt Bewegung",
        "flucht.failure":               "Misslungen — GS/2 Bewegung, Passierschlag erlitten",
        "flucht.succeeded":             "Gelungen",
        "flucht.failed":                "Misslungen",

        // Fernkampf
        "rangedAttack":                 "Fernkampf",
        "fernkampf":                    "Fernkampf",
        "fernkampf.setup":              "Fernkampf vorbereiten",
        "fernkampf.distanz":            "DISTANZ",
        "fernkampf.distanz.nah":        "Nah",
        "fernkampf.distanz.mittel":     "Mittel",
        "fernkampf.distanz.weit":       "Weit",
        "fernkampf.groesse":            "GRÖSSE",
        "fernkampf.groesse.winzig":     "Winzig",
        "fernkampf.groesse.klein":      "Klein",
        "fernkampf.groesse.mittel":     "Mittel",
        "fernkampf.groesse.gross":      "Groß",
        "fernkampf.groesse.riesig":     "Riesig",
        "fernkampf.bewegungZiel":       "BEWEGUNG ZIEL",
        "fernkampf.ziel.still":         "Still",
        "fernkampf.ziel.leicht":        "Leicht",
        "fernkampf.ziel.schnell":       "Schnell",
        "fernkampf.ziel.haken":         "Haken",
        "fernkampf.bewegungSchuetze":   "BEWEGUNG SCHÜTZE",
        "fernkampf.schuetze.steht":     "Steht",
        "fernkampf.schuetze.geht":      "Geht",
        "fernkampf.schuetze.rennt":     "Rennt",
        "fernkampf.sicht":              "SICHT",
        "fernkampf.sicht.klar":         "Klar",
        "fernkampf.sicht.stufe1":       "Stufe 1",
        "fernkampf.sicht.stufe2":       "Stufe 2",
        "fernkampf.sicht.stufe3":       "Stufe 3",
        "fernkampf.kampfgetuemmel":     "Kampfgetümmel",
        "fernkampf.zielen":             "ZIELEN",
        "fernkampf.zielen.0":           "Kein Zielen",
        "fernkampf.zielen.1":           "1 Aktion (+2)",
        "fernkampf.zielen.2":           "2 Aktionen (+4)",
        "fernkampf.vomPferd":           "VOM PFERD",
        "fernkampf.pferd.steht":        "Steht",
        "fernkampf.pferd.schritt":      "Schritt",
        "fernkampf.pferd.galopp":       "Galopp",
        "fernkampf.rangedWeapons.label":"FERNKAMPFWAFFEN",
        "source.distanz":               "Distanz",
        "source.groesse":               "Größe",
        "source.bewegungZiel":          "Bewegung Ziel",
        "source.bewegungSchuetze":      "Bewegung Schütze",
        "source.sicht":                 "Sicht",
        "source.kampfgetuemmel":        "Kampfgetümmel",
        "source.zielen":                "Zielen",
        "source.vomPferd":              "Vom Pferd",

        // Combat session
        "endCombat":                    "Kampf beenden",
        "endCombat.confirm":            "Kampf wirklich beenden?",

        // Adventure & Weather
        "adventures":                   "Abenteuer",
        "newAdventure":                 "Neues Abenteuer",
        "adventureName":                "Name",
        "adventureRegion":              "Region",
        "adventureStartDate":           "Startdatum",
        "adventureDesert":              "Wüste",
        "adventureWindy":               "Windig",
        // Makroregionen
        "macro.hoherNorden":            "Hoher Norden",
        "macro.hochgebirge":            "Hochgebirge",
        "macro.nordaventurien":         "Nordaventurien",
        "macro.zentralaventurien":      "Zentralaventurien",
        "macro.tulamidenlande":         "Tulamidenlande",
        "macro.suedaventurien":         "Südaventurien",
        "macro.tieferSueden":           "Tiefer Süden & Inseln",
        // Klima-Archetypen
        "climate.polar":                "Polar",
        "climate.subarctic":            "Subarktis",
        "climate.highMountainIce":      "Gletschergebirge",
        "climate.highMountain":         "Hochgebirge",
        "climate.coldCoast":            "Kalte Küste",
        "climate.coldContinental":      "Kalt-kontinental",
        "climate.temperate":            "Gemäßigt",
        "climate.mediterranean":        "Mediterran",
        "climate.semiArid":             "Halbwüste/Steppe",
        "climate.desert":               "Wüste",
        "climate.subtropicalHot":       "Subtropisch-heiß",
        "climate.tropicalHumid":        "Tropisch-feucht",
        "climate.tropicalSea":          "Tropische See",
        // Regionen
        "region.ewigesEis":             "Ewiges Eis",
        "region.nivesenland":           "Nivenland, Tundra",
        "region.gjalskerland":          "Gjalskerland",
        "region.ehernesSchwert":        "Höhen des Ehernen Schwerts",
        "region.raschtulswall":         "Höhen des Raschtulswalls",
        "region.thorwal":               "Thorwal",
        "region.bornland":              "Bornland",
        "region.svelltland":            "Svelltal",
        "region.orkland":               "Orkland",
        "region.mittelreich":           "Zentrales Mittelreich",
        "region.streitendeKoenigreiche": "Streitende Königreiche, Weiden",
        "region.elfenlande":            "Elfenlande",
        "region.aranien":               "Aranien",
        "region.khom":                  "Khôm",
        "region.mhanadiTal":            "Mhanadi-Tal, Unau",
        "region.almada":                "Almada",
        "region.horasreich":            "Horasreich, Liebliches Feld",
        "region.ersteSonne":            "Reich der Ersten Sonne",
        "region.zyklopeninseln":        "Zyklopeninseln",
        "region.meridiana":             "Al'Anfa, Meridiana",
        "region.echsensuempfe":         "Echsensümpfe",
        "region.maraskan":              "Maraskan",
        "region.suedmeer":              "Altoum, Gewürzinseln, Südmeer",
        "nextDay":                      "Nächster Tag",
        "generateDays":                 "Tage generieren…",
        "setDate":                      "Datum setzen…",
        "export":                       "Exportieren",
        "weather.add":                  "Wetter hinzufügen",
        "weather.empty":                "Füge Wetter hinzu, um zu beginnen",
        "weather.rules":                "Regeln",
        "adventureDefaultRegion":       "Standardregion",
        "weather.rules.title":          "Wie das Wetter funktioniert",
        "weather.rules.body":           "Nachttemperatur = Tagestemperatur minus Tagesschwankung. Trockene, klare und windstille Gegenden (Wüste, Hochgebirge) kühlen nachts stark ab; bewölkte, feuchte oder windige Gegenden (Küste, Sümpfe) kaum. Jede Region hat ein Klima, das Grundtemperatur, Schwankung, Feuchtigkeit und Wind bestimmt.",
        "weather.rules.clouds":         "Wolken halten Wärme → geringerer Abfall.",
        "weather.rules.wind":           "Wind durchmischt die Luft → geringerer Abfall.",
        "weather.rules.climate":        "Das Klima bestimmt die Schwankung bei klarem Himmel.",
        "settings":                     "Einstellungen",
        "dayCount":                     "Anzahl Tage",
        "timeJump":                     "Zeitsprung",
        "generate":                     "Generieren",
        "cancel":                       "Abbrechen",
        "create":                       "Erstellen",
        // Weather display
        "weather.clouds.none":          "Wolkenlos",
        "weather.clouds.few":           "Wenige Wolken",
        "weather.clouds.lots":          "Bewölkt",
        "weather.clouds.all":           "Bedeckt",
        "weather.wind.none":            "Windstill",
        "weather.wind.light":           "Leichter Wind",
        "weather.wind.soft":            "Sanfter Wind",
        "weather.wind.fresh":           "Frischer Wind",
        "weather.wind.cool":            "Kühler Wind",
        "weather.wind.strong":          "Starker Wind",
        "weather.wind.storm":           "Sturm",
        "weather.rain.none":            "Kein Niederschlag",
        "weather.rain.little":          "Leichter Niederschlag",
        "weather.rain.lots":            "Starker Niederschlag",
        "weather.rain.all":             "Dauerregen",
        "weather.field.clouds":         "Wolken",
        "weather.field.wind":           "Wind",
        "weather.field.rain":           "Niederschlag",
        "weather.dayTemp":              "Tag",
        "weather.nightTemp":            "Nacht",
        "weather.range":                "Schwankung",
        "weather.edited":               "bearbeitet",
        "weather.reason.dry":           "trocken",
        "weather.reason.humid":         "feucht",
        "weather.reason.clear":         "klar",
        "weather.reason.cloudy":        "Wolken",
        "weather.reason.windy":         "Wind",
        "weather.reroll":               "Neu würfeln",
        "weather.editValues":           "Werte überschreiben",
        "save":                         "Speichern",
        // Magic sections
        "groupMagic":                   "Magie & Karma",
        "spells.section":               "Zaubersprüche",
        "liturgies.section":            "Liturgien",
        "cantrips.section":             "Zaubertricks",
        "blessings.section":            "Segnungen",

        // Magic modifier sources
        "source.maintainedSpells":      "Aufrechterh. Zauber",
        "source.foreignTradition":      "Fremde Tradition",
        "source.omitGesture":           "Ohne Geste",
        "source.omitFormula":           "Ohne Formel",
        "source.bannDesEisens":         "Bann des Eisens",
        "source.distraction":           "Ablenkung",
        "source.spellModifications":    "Modifikationen",

        // Magic flow
        "castSpell":                    "Zaubern",
        "spellProbe":                   "Zauberprobe",
        "liturgyProbe":                 "Liturgieprobe",
        "spellSelection":               "Zauber wählen",
        "spellSetup":                   "Zauber vorbereiten",
        "spellCasting.banner":          "Wirkt: %@ (%d/%d)",
        "spellCasting.continue":        "Weiter wirken",
        "spellCasting.abort":           "Abbrechen",
        "spellCasting.interrupted":     "Unterbrochen!",
        "aeCost":                       "AsP-Kosten",
        "aeCost.success":               "AsP: %d",
        "aeCost.failure":               "AsP (misslungen): %d",
        "modifications":                "Modifikationen",
        "modifications.section":        "Modifikationen & Erschwernisse",
        "mod.reduceCastingTime":        "Zauberdauer senken",
        "mod.increaseCastingTime":      "Zauberdauer erhöhen",
        "mod.increaseRange":            "Reichweite erhöhen",
        "mod.reduceCost":               "Kosten senken",
        "mod.force":                    "Erzwingen",
        "mod.omitGesture":              "Ohne Geste",
        "mod.omitFormula":              "Ohne Formel",
        "mod.foreignTradition":         "Fremde Tradition",
        "mod.maintainedSpells":         "Aufrechterhaltene Zauber",
        "mod.ironCarried":              "Eisen (Stein)",
        "mod.distraction":              "Ablenkung",
        "mod.distraction.none":         "Keine",
        "mod.distraction.minor":        "Leicht (+3)",
        "mod.distraction.ship":         "Schiff (±0)",
        "mod.distraction.freefall":     "Freier Fall (−3)",
        "maxModifications":             "Max. Modifikationen: %d",
        "concentrationCheck":           "Selbstbeherrschung-Probe nötig",
    ]
}

// Convenience: short global function
func L(_ key: String) -> String {
    DSAStrings.localized(key)
}
