import Foundation

enum DSAStrings {
    static let locale = "de"

    // MARK: - Lookup

    static func localized(_ key: String) -> String {
        if locale == "de", let de = translations[key] {
            return de
        }
        return englishFallback[key] ?? key
    }

    // MARK: - Field Labels (PersonalData, Experience, DerivedValues)

    private static let englishFallback: [String: String] = [
        // Experience
        "level":                "Level",
        "totalAP":              "Total AP",
        "availableAP":          "Available AP",
        "spentAP":              "Spent AP",
        // PersonalData
        "name":                 "Name",
        "family":               "Family",
        "birthplace":           "Birthplace",
        "birthdate":            "Birthdate",
        "age":                  "Age",
        "gender":               "Gender",
        "species":              "Species",
        "height":               "Height",
        "weight":               "Weight",
        "hairColor":            "Hair Color",
        "eyeColor":             "Eye Color",
        "culture":              "Culture",
        "socialStatus":         "Social Status",
        "profession":           "Profession",
        "title":                "Title",
        "characteristics":      "Characteristics",
        // DerivedValues
        "lebensenergie":        "Life Energy",
        "schicksalspunkte":     "Fate Points",
        "astralenergie":        "Astral Energy",
        "karmaenergie":         "Karma Energy",
        "seelenkraft":          "Spirit",
        "zähigkeit":            "Toughness",
        "ausweichen":           "Dodge",
        "initiative":           "Initiative",
        "geschwindigkeit":      "Speed",
        "wundschwelle":         "Wound Threshold",
        // Section Headers
        "experience":           "Experience",
        "personalData":         "Personal Data",
        "derivedValues":        "Derived Values",
        "advantages":           "Advantages",
        "disadvantages":        "Disadvantages",
        "generalSpecialAbilities": "General Special Abilities",
        "languages":            "Languages",
        "scripts":              "Scripts",
        "combatTechniques":     "Combat Techniques",
        "combatSpecialAbilities": "Combat Special Abilities",
        "equipment":            "Equipment",
        "meleeWeapons":         "Melee Weapons",
        "rangedWeapons":        "Ranged Weapons",
        "shields":              "Shields",
        "armor":                "Armor",
        "money":                "Money",
        "mount":                "Mount",
        // Mount fields
        "mountName":            "Name",
        "mountType":            "Type",
        "mountSize":            "Size",
        "mountLifeEnergy":      "Life Energy",
        "mountInitiative":      "Initiative",
        "mountSpeed":           "Speed",
        "mountAttacks":         "Attacks",
        "mountTalents":         "Talents",
        "mountSpecialAbilities": "Special Abilities",
        // Group headers (top-level tabs)
        "groupPersonalData":    "Personal Data",
        "groupTalents":         "Talents",
        "groupCombat":          "Combat",
        "groupEquipment":       "Equipment",
        // Money
        "dukaten":              "Ducats",
        "silbertaler":          "Silver Talers",
        "heller":               "Hellers",
        "kreuzer":              "Kreuzers",
        // Combat
        "combat":               "Combat",
        "round":                "Round",
        "lifePoints":           "Life Points",
        "lifePoints.short":     "LP",
        "action":               "Action",
        "attack":               "Attack",
        "parry":                "Parry",
        "dodge":                "Dodge",
        "newAction":            "New Action",
        "newInitiative":        "New Initiative",
        "unarmed":              "Unarmed",
        "confirmation":         "Confirmation",
        "tapToRoll":            "Tap to roll",
        "modifier":             "Mod",
        "new":                  "New",
        "initiative.label":     "INITIATIVE",
        "lifePoints.label":     "LIFE POINTS",
        "action.label":         "ACTION",
        "unarmed.label":        "UNARMED",
        "selectWeapon":         "Select Weapon",
        "selectShield":         "Select Shield",
        "noShield":             "No Shield",
        "criticalSuccess":      "!!! Critical Success!",
        "criticalFumble":       "!!! Critical Fumble!",
        "success":              "Success",
        "failure":              "Failure",
        "selectEquipment":      "Select Equipment",
        "offHandWeapon":        "OFF-HAND",
        "dualAttack":           "Both Weapons",
        "singleAttack":         "One Weapon",
        "oneHanded":            "One-Handed",
        "twoHanded":            "Two-Handed (+1 TP, −1 PA)",
        "dualAttackPenalty":    "Dual-attack penalty",
        "offHandPenalty":       "Off-hand penalty",
        "advantageousPosition": "Advantageous Position (+2)",
        "fumbleSecondLost":     "Fumble! Second attack lost.",
        "selectParryWeapon":    "Parry With",
        "shields.label":        "SHIELDS",
        // Rulebook
        "rulebook":             "Rulebook",
        "backToHero":           "Back to Hero",
        "backToRulebook":       "Back to Rulebook",
        "back":                 "Back",
        "ruleNotFound":         "Rule not found",
        "ruleLoadError":        "The rule could not be loaded.",
        "effects":              "Effects",
        "searchRules":          "Search rules…",
        "searchCommands":       "Search commands…",
        "noResults":            "No results",
        // HeroList
        "heroes":               "Heroes",
        "noHeroes":             "No Heroes",
        "importHero":           "Import Hero",
        "importHint":           "Import a JSON or YAML file to add your first hero.",
        "selectHint":           "Select a hero or the rulebook from the list.",
        // TalentProbe
        "probe":                "Probe",
        "unknownTalent":        "Unknown Talent",
        // Regeneration
        "regeneration":         "Regeneration",
        "improvedRegen":        "Improved Regen.",
        // Rule categories (singular)
        "cat.advantage":        "Advantage",
        "cat.disadvantage":     "Disadvantage",
        "cat.special_ability":  "Special Ability",
        "cat.combat_technique": "Combat Technique",
        "cat.skill":            "Skill",
        "cat.condition":        "Condition",
        "cat.state":            "State",
        // Rule categories (plural)
        "cats.advantage":       "Advantages",
        "cats.disadvantage":    "Disadvantages",
        "cats.special_ability": "Special Abilities",
        "cats.combat_technique":"Combat Techniques",
        "cats.skill":           "Skills",
        "cats.condition":       "Conditions",
        "cats.state":           "States",
        "cat.spell":            "Spell",
        "cat.liturgy":          "Liturgy",
        "cats.spell":           "Spells",
        "cats.liturgy":         "Liturgies",

        "spellCheck":           "Check",
        "spellIC":              "Improvement Cost",
        "spellCastingTime":     "Casting Time",
        "spellAeCost":          "AE Cost",
        "liturgyTime":          "Liturgy Time",
        "liturgyCost":          "KP Cost",
        "spellRange":           "Range",
        "spellDuration":        "Duration",
        "spellTarget":          "Target",
        // Damage & Armor
        "takeDamage":           "Take Damage",
        "takeDamage.label":     "TAKE DAMAGE",
        "tp":                   "TP",
        "rs":                   "RS",
        "equip":                "Equip",
        "unequip":              "Unequip",
        "armorSelection":       "Armor Selection",
        "armorSelection.label": "ARMOR",
        "continue":             "Continue",
        "confirm":              "Confirm",
        "noArmor":              "No armor available",
        "equipped":             "Equipped",
        "protectionValue":      "RS",
        "encumbrance":          "BE",
        "lpLost":               "LP lost",
        "absorbed":             "Armor absorbs all damage",
        "changeLoadout":        "Change Loadout",
        // Combat Maneuvers
        "combatSetup":          "Combat Setup",
        "combatSetup.label":    "COMBAT SETUP",
        "formation.label":      "FORMATION",
        "mount.label":          "MOUNT",
        "mounted":              "Mounted",
        "announcement":         "Announcement",
        "announcement.label":   "MANEUVER",
        "maneuver.normal":      "Normal",
        "maneuver.finte":       "Feint",
        "maneuver.wuchtschlag": "Powerful Blow",
        "maneuver.vorstoss":    "Thrust",
        "maneuver.schildspalter":"Shield Splitter",
        "maneuver.sturmangriff":"Mounted Charge",
        "plaenkler":            "Skirmisher Formation",
        "plaenklerAT":          "+1 AT",
        "plaenklerAW":          "+1 Dodge",
        "noDefenseWarning":     "No defense this round!",
        "opponentPA":           "Opponent PA",
        "damageBonus":          "Damage",
        "targetShield":         "Damage targets shield SP",
        "mightyBlow":           "Mighty Blow: On hit, medium/small opponents must pass Feat of Strength or fall prone (penalty -%d).",
        "mightyBlowNoPenalty":  "Mighty Blow: On hit, medium/small opponents must pass Feat of Strength or fall prone. Parry does not help — only Dodge avoids it entirely.",
        "calculation.label":    "CALCULATION",
        "additional.label":     "ADDITIONAL",
        "source.basis":         "Base",
        "source.belastung":     "Encumbrance",
        "source.schmerz":       "Pain",
        "source.vorteilhaft":   "Adv. Position",
        "source.golgariten":    "Golgariten",
        "source.plaenkler":     "Skirmisher",
        "source.finte":         "Feint",
        "source.wuchtschlag":   "Powerful Blow",
        "source.vorstoss":      "Thrust",
        "source.sturmangriff":  "Mounted Charge",
        "source.dualAttack":    "Dual-attack",
        "source.offHand":       "Off-hand",
        "source.additional":    "Additional",
        "source.mounted":       "Mounted",
        "source.shield":        "Shield",
        "mountAttacks.label":   "MOUNT ATTACKS",
        "aufmerksamkeitHint":   "Aufmerksamkeit: +2 to avoid surprise",
        "schmerz.label":        "Pain",
        "schmerz.none":         "No pain",
        "schmerz.I":            "Pain I",
        "schmerz.II":           "Pain II",
        "schmerz.III":          "Pain III",
        "schmerz.IV":           "Incapacitated",
        "chargeBonus":          "Charge bonus",
        // Subfield labels (weapons, armor)
        "combatTechnique":      "Combat Technique",
        "damage":               "Damage",
        "reach":                "Reach",
        "range":                "Range",
        "structurePoints":      "SP",
        // Combat section labels
        "meleeWeapons.label":   "MELEE WEAPONS",
        "basis.label":          "BASICS",
        "damage.label":         "DAMAGE",
        "mainWeapon":           "MAIN WEAPON",
        "shieldOption":         "SHIELD",
        "hero":                 "Hero",
        // Misc UI
        "current":              "Current",
        "tierPrefix":           "Level",
        "rolling":              "Rolling...",
        "confirmIni":           "Confirm  →  INI",
        "roundPrefix":          "Round",
        "apPrefix":             "AP",
        "levelsPrefix":         "Levels",
        "importError":          "Import Error",
        "unknownError":         "An unknown error occurred.",
        "ok":                   "OK",
    ]

    private static let translations: [String: String] = [
        // Experience
        "level":                "Stufe",
        "totalAP":              "AP gesamt",
        "availableAP":          "AP verfügbar",
        "spentAP":              "AP ausgegeben",
        // PersonalData
        "name":                 "Name",
        "family":               "Familie",
        "birthplace":           "Geburtsort",
        "birthdate":            "Geburtsdatum",
        "age":                  "Alter",
        "gender":               "Geschlecht",
        "species":              "Spezies",
        "height":               "Größe",
        "weight":               "Gewicht",
        "hairColor":            "Haarfarbe",
        "eyeColor":             "Augenfarbe",
        "culture":              "Kultur",
        "socialStatus":         "Sozialstatus",
        "profession":           "Profession",
        "title":                "Titel",
        "characteristics":      "Eigenschaften",
        // DerivedValues
        "lebensenergie":        "Lebensenergie",
        "schicksalspunkte":     "Schicksalspunkte",
        "astralenergie":        "Astralenergie",
        "karmaenergie":         "Karmaenergie",
        "seelenkraft":          "Seelenkraft",
        "zähigkeit":            "Zähigkeit",
        "ausweichen":           "Ausweichen",
        "initiative":           "Initiative",
        "geschwindigkeit":      "Geschwindigkeit",
        "wundschwelle":         "Wundschwelle",
        // Section Headers
        "experience":           "Erfahrung",
        "personalData":         "Persönliche Daten",
        "derivedValues":        "Abgeleitete Werte",
        "advantages":           "Vorteile",
        "disadvantages":        "Nachteile",
        "generalSpecialAbilities": "Allgemeine Sonderfertigkeiten",
        "languages":            "Sprachen",
        "scripts":              "Schriften",
        "combatTechniques":     "Kampftechniken",
        "combatSpecialAbilities": "Kampf-Sonderfertigkeiten",
        "equipment":            "Ausrüstung",
        "meleeWeapons":         "Nahkampfwaffen",
        "rangedWeapons":        "Fernkampfwaffen",
        "shields":              "Schilde",
        "armor":                "Rüstungen",
        "money":                "Geld",
        "mount":                "Reittier",
        // Mount fields
        "mountName":            "Name",
        "mountType":            "Art",
        "mountSize":            "Größe",
        "mountLifeEnergy":      "Lebensenergie",
        "mountInitiative":      "Initiative",
        "mountSpeed":           "Geschwindigkeit",
        "mountAttacks":         "Angriffe",
        "mountTalents":         "Talente",
        "mountSpecialAbilities": "Sonderfertigkeiten",
        // Group headers (top-level tabs)
        "groupPersonalData":    "Persönliche Daten",
        "groupTalents":         "Talente",
        "groupCombat":          "Kampf",
        "groupEquipment":       "Ausrüstung",
        // Money
        "dukaten":              "Dukaten",
        "silbertaler":          "Silbertaler",
        "heller":               "Heller",
        "kreuzer":              "Kreuzer",
        // Combat
        "combat":               "Kampf",
        "round":                "Runde",
        "lifePoints":           "Lebenspunkte",
        "lifePoints.short":     "LP",
        "action":               "Aktion",
        "attack":               "Angriff",
        "parry":                "Parieren",
        "dodge":                "Ausweichen",
        "newAction":            "Neue Aktion",
        "newInitiative":        "Neue Initiative",
        "unarmed":              "Waffenlos",
        "confirmation":         "Bestätigung",
        "tapToRoll":            "Antippen zum Würfeln",
        "modifier":             "Mod",
        "new":                  "Neu",
        "initiative.label":     "INITIATIVE",
        "lifePoints.label":     "LEBENSPUNKTE",
        "action.label":         "AKTION",
        "unarmed.label":        "WAFFENLOS",
        "selectWeapon":         "Waffe wählen",
        "selectShield":         "Schild wählen",
        "noShield":             "Kein Schild",
        "criticalSuccess":      "!!! Kritischer Erfolg!",
        "criticalFumble":       "!!! Kritischer Patzer!",
        "success":              "Erfolg",
        "failure":              "Misserfolg",
        "selectEquipment":      "Ausrüstung wählen",
        "offHandWeapon":        "NEBENHAND",
        "dualAttack":           "Beide Waffen",
        "singleAttack":         "Eine Waffe",
        "oneHanded":            "Einhändig",
        "twoHanded":            "Zweihändig (+1 TP, −1 PA)",
        "dualAttackPenalty":    "Beidhändig-Abzug",
        "offHandPenalty":       "Nebenhand-Abzug",
        "advantageousPosition": "Vorteilhafte Position (+2)",
        "fumbleSecondLost":     "Patzer! Zweiter Angriff entfällt.",
        "selectParryWeapon":    "Parieren mit",
        "shields.label":        "SCHILDE",
        // Rulebook
        "rulebook":             "Regelbuch",
        "backToHero":           "Zurück zum Helden",
        "backToRulebook":       "Zurück zum Regelbuch",
        "back":                 "Zurück",
        "ruleNotFound":         "Regel nicht gefunden",
        "ruleLoadError":        "Die Regel konnte nicht geladen werden.",
        "effects":              "Effekte",
        "searchRules":          "Regel suchen…",
        "searchCommands":       "Befehl suchen…",
        "noResults":            "Keine Ergebnisse",
        // HeroList
        "heroes":               "Helden",
        "noHeroes":             "Keine Helden",
        "importHero":           "Held importieren",
        "importHint":           "Importiere eine JSON- oder YAML-Datei, um deinen ersten Helden hinzuzufügen.",
        "selectHint":           "Wähle einen Helden oder das Regelbuch aus der Liste.",
        // TalentProbe
        "probe":                "Probe",
        "unknownTalent":        "Unbekanntes Talent",
        // Regeneration
        "regeneration":         "Regenerieren",
        "improvedRegen":        "Verb. Regen.",
        // Rule categories (singular)
        "cat.advantage":        "Vorteil",
        "cat.disadvantage":     "Nachteil",
        "cat.special_ability":  "Sonderfertigkeit",
        "cat.combat_technique": "Kampftechnik",
        "cat.skill":            "Talent",
        "cat.condition":        "Zustand",
        "cat.state":            "Status",
        // Rule categories (plural)
        "cats.advantage":       "Vorteile",
        "cats.disadvantage":    "Nachteile",
        "cats.special_ability": "Sonderfertigkeiten",
        "cats.combat_technique":"Kampftechniken",
        "cats.skill":           "Talente",
        "cats.condition":       "Zustände",
        "cats.state":           "Status",
        "cat.spell":            "Zauber",
        "cat.liturgy":          "Liturgie",
        "cats.spell":           "Zauber",
        "cats.liturgy":         "Liturgien",

        "spellCheck":           "Probe",
        "spellIC":              "Steigerungsfaktor",
        "spellCastingTime":     "Zauberdauer",
        "spellAeCost":          "AsP-Kosten",
        "liturgyTime":          "Liturgiedauer",
        "liturgyCost":          "KaP-Kosten",
        "spellRange":           "Reichweite",
        "spellDuration":        "Wirkungsdauer",
        "spellTarget":          "Zielkategorie",
        // Damage & Armor
        "takeDamage":           "Schaden nehmen",
        "takeDamage.label":     "SCHADEN NEHMEN",
        "tp":                   "TP",
        "rs":                   "RS",
        "equip":                "Anlegen",
        "unequip":              "Ablegen",
        "armorSelection":       "Rüstungsauswahl",
        "armorSelection.label": "RÜSTUNG",
        "continue":             "Weiter",
        "confirm":              "Bestätigen",
        "noArmor":              "Keine Rüstung vorhanden",
        "equipped":             "Angelegt",
        "protectionValue":      "RS",
        "encumbrance":          "BE",
        "lpLost":               "LP verloren",
        "absorbed":             "Rüstung absorbiert allen Schaden",
        "changeLoadout":        "Ausrüstung wechseln",
        // Combat Maneuvers
        "combatSetup":          "Kampfvorbereitung",
        "combatSetup.label":    "KAMPFVORBEREITUNG",
        "formation.label":      "FORMATION",
        "mount.label":          "REITTIER",
        "mounted":              "Beritten",
        "announcement":         "Ansage",
        "announcement.label":   "MANÖVER",
        "maneuver.normal":      "Normal",
        "maneuver.finte":       "Finte",
        "maneuver.wuchtschlag": "Wuchtschlag",
        "maneuver.vorstoss":    "Vorstoß",
        "maneuver.schildspalter":"Schildspalter",
        "maneuver.sturmangriff":"Sturmangriff",
        "plaenkler":            "Plänkler-Formation",
        "plaenklerAT":          "+1 AT",
        "plaenklerAW":          "+1 AW",
        "noDefenseWarning":     "Keine Verteidigung diese Runde!",
        "opponentPA":           "Gegner PA",
        "damageBonus":          "Schaden",
        "targetShield":         "Schaden gegen Schild-SP",
        "mightyBlow":           "Mächtiger Schlag: Bei Treffer müssen Gegner (mittel/klein) Kraftakt bestehen oder erhalten Status Liegend (Erschwernis -%d). Parade hilft nicht — nur Ausweichen schützt vollständig.",
        "mightyBlowNoPenalty":  "Mächtiger Schlag: Bei Treffer müssen Gegner (mittel/klein) Kraftakt bestehen oder erhalten Status Liegend. Parade hilft nicht — nur Ausweichen schützt vollständig.",
        "calculation.label":    "BERECHNUNG",
        "additional.label":     "ZUSÄTZLICH",
        "source.basis":         "Basis",
        "source.belastung":     "Belastung",
        "source.schmerz":       "Schmerz",
        "source.vorteilhaft":   "Vorteilh. Pos.",
        "source.golgariten":    "Golgariten",
        "source.plaenkler":     "Plänkler",
        "source.finte":         "Finte",
        "source.wuchtschlag":   "Wuchtschlag",
        "source.vorstoss":      "Vorstoß",
        "source.sturmangriff":  "Sturmangriff",
        "source.dualAttack":    "Beidhändig",
        "source.offHand":       "Nebenhand",
        "source.additional":    "Zusätzlich",
        "source.mounted":       "Beritten",
        "source.shield":        "Schild",
        "mountAttacks.label":   "REITTIER-ANGRIFFE",
        "aufmerksamkeitHint":   "Aufmerksamkeit: +2 auf Überraschung vermeiden",
        "schmerz.label":        "Schmerz",
        "schmerz.none":         "Kein Schmerz",
        "schmerz.I":            "Schmerz I",
        "schmerz.II":           "Schmerz II",
        "schmerz.III":          "Schmerz III",
        "schmerz.IV":           "Handlungsunfähig",
        "chargeBonus":          "Sturmangriffsbonus",
        // Subfield labels (weapons, armor)
        "combatTechnique":      "Kampftechnik",
        "damage":               "Schaden",
        "reach":                "Reichweite",
        "range":                "Reichweite",
        "structurePoints":      "SP",
        // Combat section labels
        "meleeWeapons.label":   "NAHKAMPFWAFFEN",
        "basis.label":          "BASIS",
        "damage.label":         "SCHADEN",
        "mainWeapon":           "HAUPTWAFFE",
        "shieldOption":         "SCHILD",
        "hero":                 "Held",
        // Misc UI
        "current":              "Aktuell",
        "tierPrefix":           "Stufe",
        "rolling":              "Würfeln...",
        "confirmIni":           "Bestätigen  →  INI",
        "roundPrefix":          "Runde",
        "apPrefix":             "AP",
        "levelsPrefix":         "Stufen",
        "importError":          "Importfehler",
        "unknownError":         "Ein unbekannter Fehler ist aufgetreten.",
        "ok":                   "OK",
    ]
}

// Convenience: short global function
func L(_ key: String) -> String {
    DSAStrings.localized(key)
}
