"""Collect every ruling from the draft rule files and write RULINGS.md.

    python3 scripts/rules_review/rulings.py          # rewrite specs/rules/RULINGS.md
    python3 scripts/rules_review/rulings.py --check  # fail if RULINGS.md is stale or a ruling is malformed

A ruling is open until its `answer` is filled in. Answering one is an edit to the rule file:
write an option letter or your own words into `answer:`. The next pass sets `status: decided`
and `decided: { by, date }` from the commit that added the answer, and updates the rule's
effects and situations to match.
"""

import re
import sys

import yaml

import rulefiles as rf

ROOT = rf.ROOT
OUT = ROOT / "RULINGS.md"


def rule_files():
    return rf.rule_paths()


def rulings_in(path):
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if isinstance(data, list):              # rulings.yaml: the shared ones
        return "shared", data
    return data["id"], data.get("rulings") or []


def line_of(path, ruling_id):
    for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if re.match(rf"\s*-\s*id:\s*{re.escape(ruling_id)}\s*$", line):
            return n
    return 1


def problems_of(r):
    out = []
    if r.get("status") not in ("open", "decided"):
        out.append("status must be open or decided")
    if r.get("status") == "decided" and not r.get("decided"):
        out.append("decided without `decided: { by, date }`")
    if r.get("status") == "open" and r.get("options") and r.get("recommended") not in r["options"]:
        out.append("recommended is not one of the options")
    return out


def collect():
    items = []
    for path in rule_files():
        owner, rulings = rulings_in(path)
        for r in rulings:
            rel = path.relative_to(ROOT)
            items.append({
                "owner": owner, "path": rel, "line": line_of(path, r["id"]), **r,
                "answered": r.get("status") == "open" and r.get("answer") not in (None, ""),
            })
    return items


def one_line(text):
    return " ".join(str(text).split())


def render(items):
    open_ = [r for r in items if r["status"] == "open" and not r["answered"]]
    answered = [r for r in items if r["answered"]]
    decided = [r for r in items if r["status"] == "decided"]
    md = [
        "# Rulings",
        "",
        "Generated by `rulings.py` from the rule files — do not edit here. To answer a ruling, open",
        "the file at the line given and write an option letter or your own words into `answer:`.",
        "",
        f"**{len(open_)} open · {len(answered)} answered, to process · {len(decided)} decided**",
        "",
    ]
    if open_:
        md += ["## Open", ""]
        for r in open_:
            md += [f"### `{r['owner']}` · {r['id']}", "",
                   f"Answer in [`{r['path']}:{r['line']}`](./{r['path']}#L{r['line']})", "",
                   f"**{one_line(r['question'])}**", ""]
            if r.get("context"):
                md += [one_line(r["context"]), ""]
            if r.get("situations"):
                md += ["Situations: " + ", ".join(r["situations"]), ""]
            for key, opt in (r.get("options") or {}).items():
                mark = " — *recommended*" if key == r.get("recommended") else ""
                md.append(f"- **{key}** {opt['says']} *App:* {opt['app']}{mark}")
            if r.get("whyRecommended"):
                md += ["", f"Why {r['recommended']}: {one_line(r['whyRecommended'])}"]
            md.append("")
    if answered:
        md += ["## Answered, to process", ""]
        md += [f"- `{r['owner']}` · {r['id']}: {one_line(r['answer'])}" for r in answered]
        md.append("")
    if decided:
        md += ["## Decided", "", "| Rule | Ruling | Answer | By |", "|---|---|---|---|"]
        for r in decided:
            d = r["decided"]
            md.append(f"| `{r['owner']}` | {r['id']} | {one_line(r['answer'])} | {d['by']}, {d['date']} |")
        md.append("")
    return "\n".join(md)


def main():
    items = collect()
    errors = [f"{r['path']}:{r['line']} {r['id']}: {p}" for r in items for p in problems_of(r)]
    text = render(items)
    if "--check" in sys.argv:
        if OUT.exists() and OUT.read_text(encoding="utf-8") != text:
            errors.append("RULINGS.md is stale: run rulings.py")
        for e in errors:
            print(e, file=sys.stderr)
        sys.exit(1 if errors else 0)
    for e in errors:
        print(e, file=sys.stderr)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT.parents[1])}")


if __name__ == "__main__":
    main()
