import Foundation

enum DSAStrings {
    static let locale = "de"

    // MARK: - Lookup

    static func localized(_ key: String) -> String {
        if locale == "de", let de = translations[key] {
            return de
        }
        return englishFallback[key] ?? key
    }

    // MARK: - Field Labels (PersonalData, Experience, DerivedValues)

    private static let englishFallback: [String: String] = [
        // Experience
        "level":                "Level",
        "totalAP":              "Total AP",
        "availableAP":          "Available AP",
        "spentAP":              "Spent AP",
        // PersonalData
        "name":                 "Name",
        "family":               "Family",
        "birthplace":           "Birthplace",
        "birthdate":            "Birthdate",
        "age":                  "Age",
        "gender":               "Gender",
        "species":              "Species",
        "height":               "Height",
        "weight":               "Weight",
        "hairColor":            "Hair Color",
        "eyeColor":             "Eye Color",
        "culture":              "Culture",
        "socialStatus":         "Social Status",
        "profession":           "Profession",
        "title":                "Title",
        "characteristics":      "Characteristics",
        // DerivedValues
        "lebensenergie":        "Life Energy",
        "schicksalspunkte":     "Fate Points",
        "astralenergie":        "Astral Energy",
        "karmaenergie":         "Karma Energy",
        "seelenkraft":          "Spirit",
        "zähigkeit":            "Toughness",
        "ausweichen":           "Dodge",
        "initiative":           "Initiative",
        "geschwindigkeit":      "Speed",
        "wundschwelle":         "Wound Threshold",
        // Section Headers
        "experience":           "Experience",
        "personalData":         "Personal Data",
        "derivedValues":        "Derived Values",
        "advantages":           "Advantages",
        "disadvantages":        "Disadvantages",
        "generalSpecialAbilities": "General Special Abilities",
        "languages":            "Languages",
        "scripts":              "Scripts",
        "combatTechniques":     "Combat Techniques",
        "combatSpecialAbilities": "Combat Special Abilities",
        "equipment":            "Equipment",
        "meleeWeapons":         "Melee Weapons",
        "rangedWeapons":        "Ranged Weapons",
        "shields":              "Shields",
        "armor":                "Armor",
        "money":                "Money",
        "mount":                "Mount",
        // Mount fields
        "mountName":            "Name",
        "mountType":            "Type",
        "mountSize":            "Size",
        "mountLifeEnergy":      "Life Energy",
        "mountInitiative":      "Initiative",
        "mountSpeed":           "Speed",
        "mountAttacks":         "Attacks",
        "mountTalents":         "Talents",
        "mountSpecialAbilities": "Special Abilities",
        // Group headers (top-level tabs)
        "groupPersonalData":    "Personal Data",
        "groupTalents":         "Talents",
        "groupCombat":          "Combat",
        "groupEquipment":       "Equipment",
        // Money
        "dukaten":              "Ducats",
        "silbertaler":          "Silver Talers",
        "heller":               "Hellers",
        "kreuzer":              "Kreuzers",
        // Combat
        "combat":               "Combat",
        "round":                "Round",
        "lifePoints":           "Life Points",
        "action":               "Action",
        "attack":               "Attack",
        "parry":                "Parry",
        "dodge":                "Dodge",
        "newAction":            "New Action",
        "newInitiative":        "New Initiative",
        "unarmed":              "Unarmed",
        "confirmation":         "Confirmation",
        "tapToRoll":            "Tap to roll",
        "modifier":             "Mod",
        "new":                  "New",
        "initiative.label":     "INITIATIVE",
        "lifePoints.label":     "LIFE POINTS",
        "action.label":         "ACTION",
        "unarmed.label":        "UNARMED",
        "selectWeapon":         "Select Weapon",
        // Rulebook
        "rulebook":             "Rulebook",
        "backToHero":           "Back to Hero",
        "backToRulebook":       "Back to Rulebook",
        "back":                 "Back",
        "ruleNotFound":         "Rule not found",
        "ruleLoadError":        "The rule could not be loaded.",
        "effects":              "Effects",
        "searchRules":          "Search rules…",
        "searchCommands":       "Search commands…",
        "noResults":            "No results",
        // HeroList
        "heroes":               "Heroes",
        "noHeroes":             "No Heroes",
        "importHero":           "Import Hero",
        "importHint":           "Import a JSON or YAML file to add your first hero.",
        "selectHint":           "Select a hero or the rulebook from the list.",
        // TalentProbe
        "probe":                "Probe",
        "unknownTalent":        "Unknown Talent",
        // Regeneration
        "regeneration":         "Regeneration",
        "improvedRegen":        "Improved Regen.",
        // Rule categories (singular)
        "cat.advantage":        "Advantage",
        "cat.disadvantage":     "Disadvantage",
        "cat.special_ability":  "Special Ability",
        "cat.combat_technique": "Combat Technique",
        "cat.skill":            "Skill",
        "cat.condition":        "Condition",
        "cat.state":            "State",
        // Rule categories (plural)
        "cats.advantage":       "Advantages",
        "cats.disadvantage":    "Disadvantages",
        "cats.special_ability": "Special Abilities",
        "cats.combat_technique":"Combat Techniques",
        "cats.skill":           "Skills",
        "cats.condition":       "Conditions",
        "cats.state":           "States",
        "cat.spell":            "Spell",
        "cat.liturgy":          "Liturgy",
        "cats.spell":           "Spells",
        "cats.liturgy":         "Liturgies",

        "spellCheck":           "Check",
        "spellIC":              "Improvement Cost",
        "spellCastingTime":     "Casting Time",
        "spellAeCost":          "AE Cost",
        "liturgyTime":          "Liturgy Time",
        "liturgyCost":          "KP Cost",
        "spellRange":           "Range",
        "spellDuration":        "Duration",
        "spellTarget":          "Target",
        // Damage & Armor
        "takeDamage":           "Take Damage",
        "takeDamage.label":     "TAKE DAMAGE",
        "tp":                   "TP",
        "rs":                   "RS",
        "equip":                "Equip",
        "unequip":              "Unequip",
        "armorSelection":       "Armor Selection",
        "armorSelection.label": "ARMOR",
        "continue":             "Continue",
        "confirm":              "Confirm",
        "noArmor":              "No armor available",
        "equipped":             "Equipped",
        "protectionValue":      "RS",
        "encumbrance":          "BE",
        "lpLost":               "LP lost",
        "absorbed":             "Armor absorbs all damage",
    ]

    private static let translations: [String: String] = [
        // Experience
        "level":                "Stufe",
        "totalAP":              "AP gesamt",
        "availableAP":          "AP verfügbar",
        "spentAP":              "AP ausgegeben",
        // PersonalData
        "name":                 "Name",
        "family":               "Familie",
        "birthplace":           "Geburtsort",
        "birthdate":            "Geburtsdatum",
        "age":                  "Alter",
        "gender":               "Geschlecht",
        "species":              "Spezies",
        "height":               "Größe",
        "weight":               "Gewicht",
        "hairColor":            "Haarfarbe",
        "eyeColor":             "Augenfarbe",
        "culture":              "Kultur",
        "socialStatus":         "Sozialstatus",
        "profession":           "Profession",
        "title":                "Titel",
        "characteristics":      "Eigenschaften",
        // DerivedValues
        "lebensenergie":        "Lebensenergie",
        "schicksalspunkte":     "Schicksalspunkte",
        "astralenergie":        "Astralenergie",
        "karmaenergie":         "Karmaenergie",
        "seelenkraft":          "Seelenkraft",
        "zähigkeit":            "Zähigkeit",
        "ausweichen":           "Ausweichen",
        "initiative":           "Initiative",
        "geschwindigkeit":      "Geschwindigkeit",
        "wundschwelle":         "Wundschwelle",
        // Section Headers
        "experience":           "Erfahrung",
        "personalData":         "Persönliche Daten",
        "derivedValues":        "Abgeleitete Werte",
        "advantages":           "Vorteile",
        "disadvantages":        "Nachteile",
        "generalSpecialAbilities": "Allgemeine Sonderfertigkeiten",
        "languages":            "Sprachen",
        "scripts":              "Schriften",
        "combatTechniques":     "Kampftechniken",
        "combatSpecialAbilities": "Kampf-Sonderfertigkeiten",
        "equipment":            "Ausrüstung",
        "meleeWeapons":         "Nahkampfwaffen",
        "rangedWeapons":        "Fernkampfwaffen",
        "shields":              "Schilde",
        "armor":                "Rüstungen",
        "money":                "Geld",
        "mount":                "Reittier",
        // Mount fields
        "mountName":            "Name",
        "mountType":            "Art",
        "mountSize":            "Größe",
        "mountLifeEnergy":      "Lebensenergie",
        "mountInitiative":      "Initiative",
        "mountSpeed":           "Geschwindigkeit",
        "mountAttacks":         "Angriffe",
        "mountTalents":         "Talente",
        "mountSpecialAbilities": "Sonderfertigkeiten",
        // Group headers (top-level tabs)
        "groupPersonalData":    "Persönliche Daten",
        "groupTalents":         "Talente",
        "groupCombat":          "Kampf",
        "groupEquipment":       "Ausrüstung",
        // Money
        "dukaten":              "Dukaten",
        "silbertaler":          "Silbertaler",
        "heller":               "Heller",
        "kreuzer":              "Kreuzer",
        // Combat
        "combat":               "Kampf",
        "round":                "Runde",
        "lifePoints":           "Lebenspunkte",
        "action":               "Aktion",
        "attack":               "Angriff",
        "parry":                "Parieren",
        "dodge":                "Ausweichen",
        "newAction":            "Neue Aktion",
        "newInitiative":        "Neue Initiative",
        "unarmed":              "Waffenlos",
        "confirmation":         "Bestätigung",
        "tapToRoll":            "Antippen zum Würfeln",
        "modifier":             "Mod",
        "new":                  "Neu",
        "initiative.label":     "INITIATIVE",
        "lifePoints.label":     "LEBENSPUNKTE",
        "action.label":         "AKTION",
        "unarmed.label":        "WAFFENLOS",
        "selectWeapon":         "Waffe wählen",
        // Rulebook
        "rulebook":             "Regelbuch",
        "backToHero":           "Zurück zum Helden",
        "backToRulebook":       "Zurück zum Regelbuch",
        "back":                 "Zurück",
        "ruleNotFound":         "Regel nicht gefunden",
        "ruleLoadError":        "Die Regel konnte nicht geladen werden.",
        "effects":              "Effekte",
        "searchRules":          "Regel suchen…",
        "searchCommands":       "Befehl suchen…",
        "noResults":            "Keine Ergebnisse",
        // HeroList
        "heroes":               "Helden",
        "noHeroes":             "Keine Helden",
        "importHero":           "Held importieren",
        "importHint":           "Importiere eine JSON- oder YAML-Datei, um deinen ersten Helden hinzuzufügen.",
        "selectHint":           "Wähle einen Helden oder das Regelbuch aus der Liste.",
        // TalentProbe
        "probe":                "Probe",
        "unknownTalent":        "Unbekanntes Talent",
        // Regeneration
        "regeneration":         "Regenerieren",
        "improvedRegen":        "Verb. Regen.",
        // Rule categories (singular)
        "cat.advantage":        "Vorteil",
        "cat.disadvantage":     "Nachteil",
        "cat.special_ability":  "Sonderfertigkeit",
        "cat.combat_technique": "Kampftechnik",
        "cat.skill":            "Talent",
        "cat.condition":        "Zustand",
        "cat.state":            "Status",
        // Rule categories (plural)
        "cats.advantage":       "Vorteile",
        "cats.disadvantage":    "Nachteile",
        "cats.special_ability": "Sonderfertigkeiten",
        "cats.combat_technique":"Kampftechniken",
        "cats.skill":           "Talente",
        "cats.condition":       "Zustände",
        "cats.state":           "Status",
        "cat.spell":            "Zauber",
        "cat.liturgy":          "Liturgie",
        "cats.spell":           "Zauber",
        "cats.liturgy":         "Liturgien",

        "spellCheck":           "Probe",
        "spellIC":              "Steigerungsfaktor",
        "spellCastingTime":     "Zauberdauer",
        "spellAeCost":          "AsP-Kosten",
        "liturgyTime":          "Liturgiedauer",
        "liturgyCost":          "KaP-Kosten",
        "spellRange":           "Reichweite",
        "spellDuration":        "Wirkungsdauer",
        "spellTarget":          "Zielkategorie",
        // Damage & Armor
        "takeDamage":           "Schaden nehmen",
        "takeDamage.label":     "SCHADEN NEHMEN",
        "tp":                   "TP",
        "rs":                   "RS",
        "equip":                "Anlegen",
        "unequip":              "Ablegen",
        "armorSelection":       "Rüstungsauswahl",
        "armorSelection.label": "RÜSTUNG",
        "continue":             "Weiter",
        "confirm":              "Bestätigen",
        "noArmor":              "Keine Rüstung vorhanden",
        "equipped":             "Angelegt",
        "protectionValue":      "RS",
        "encumbrance":          "BE",
        "lpLost":               "LP verloren",
        "absorbed":             "Rüstung absorbiert allen Schaden",
    ]
}

// Convenience: short global function
func L(_ key: String) -> String {
    DSAStrings.localized(key)
}
